language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
matrix:
  allow_failures:
    - python: "pypy"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run trial rsftp
after_success:
  - coveralls
